### ISSUE TITLE
jQuery website doesn't showing the latest releases

### ISSUE THREAD

**Issue by edwin-egalite** [jquery/jquery.com#100]
The website does not show the latest 1.11.3 and 2.1.4 releases.

**Comment by arthurvr** [comment]
It's updated, but nobody deployed yet: https://github.com/jquery/jquery.com/commit/b073845f11661c3f705476f242d8cdcd55ff1047. @timmywil Is there a reason you didn't deploy it?

**Comment by timmywil** [comment]
There was an issue with deployment. I'll try to get it deployed.

**Comment by timmywil** [comment]
Committed (5083d59715e812784d101cf1d57bd0c420a19fe6), but I'll make sure the deployment goes through before closing this.

**Comment by timmywil** [comment]
Deployment successful. Thanks for the reminder.
