### ISSUE TITLE
Wrong site link name on event.which

### ISSUE THREAD

**Issue by amarchino** [jquery/jquery.com#105]
In the documentation page for [event.which](http://api.jquery.com/event.which/) the visualized name for the link to the Mozilla Developed Network is incorrectly spelled as MDC, whereas it should be MDN.

**Comment by arthurvr** [comment]
I'll fix this one this evening. Thanks for letting us know.

**Comment by arthurvr** [comment]
Done: https://github.com/jquery/api.jquery.com/issues/769. Thanks for reporting!

Side: this is the jquery.com repo, this issue should've been in the api.jquery.com repo.
