### ISSUE TITLE
Add Edge to the jQuery core support matrix

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery.com#115]
We're testing on Edge (see http://swarm.jquery.org/project/jquery) but don't have it listed at https://jquery.com/browser-support/ . The layout there is getting rather wide, maybe we should go to a vertical layout.

/cc @jacobrossi

**Comment by mzgol** [comment]
I wouldn't introduce any major changes here as all that is handled in the jquery-3 branch, see https://github.com/jquery/jquery.com/pull/111#issuecomment-153094102

I'll just add an Edge column for now. I can merge Chrome with Firefox as they have the same support strategy so the number of columns won't increase.

**Comment by mzgol** [comment]
The page has been updated.

**Comment by dmethvin** [comment]
Thanks @mzgol!
