### ISSUE TITLE
error in example in: https://jqueryui.com/tabs/

### ISSUE THREAD

**Issue by daep996** [jquery/jquery.com#118]
Hello:

I found an error in: https://jqueryui.com/tabs/
If you select the option "Vertical Tabs functionality" apear correctly, but if you can copy and paste the code of the option "Viwe source", all the URL of JavaScript and CSS lack "HTTP:" in the lines 6, 7 and 8.

Should see:
  link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"

  script src="http://code.jquery.com/jquery-1.10.2.js"

  script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"

**Comment by scottgonzalez** [comment]
That is not a bug. That's the actual source code for the examples. Also, this is the bug tracker for jquery.com, not jqueryui.com.

**Comment by daep996** [comment]
upps, excuse me, then, Where I can write to correct this small error on the page?

**Comment by scottgonzalez** [comment]
As I said, there is no error. These are protocol relative URLs.
