### ISSUE TITLE
The ':first' and 'first()' documantations are confusing

### ISSUE THREAD

**Issue by RandallFlagg** [jquery/jquery.com#120]
https://api.jquery.com/first-selector/
https://api.jquery.com/first/

When reading this 2 docs the word elements once is referring to XML node(selector) and the other one is referring to array element(function).

The meaning should be unambiguous.

thanks

**Comment by dmethvin** [comment]
I think we use the term *matched element* pretty consistently throughout the documentation. Can you suggest some wording on one or both pages that would make it less confusing?

**Comment by RandallFlagg** [comment]
function: Reduce the set of matched elements to the first in the set.
selector: Selects the first matched element.

I would change the selector description to something like:
Selects the first matched node element.

**Comment by mgol** [comment]
BTW, issues with https://api.jquery.com should be reported at https://github.com/jquery/api.jquery.com/, this repository keeps only a couple of static pages directly under https://jquery.com.

**Comment by dmethvin** [comment]
You're right, I didn't even notice since I track both repos.  @RandallFlagg can you open a ticket over on the api.jquery.com site?

**Comment by kswedberg** [comment]
@RandallFlagg , would "Selects the first matched DOM element" be acceptable? "DOM element" seems less ambiguous to me than "node element."

**Comment by RandallFlagg** [comment]
@kswedberg it sounds good.
@dmethvin opened.

continues here:
https://github.com/jquery/api.jquery.com/issues/894
