### ISSUE TITLE
[Fixed] Download: Add a "Downloading jQuery using npm" section

### ISSUE THREAD

**Issue by mgol** [jquery/jquery.com#122]
jQuery now uses npm to internally manage its dependencies instead of Bower, jQuery plugins are now advised to get published to npm etc. and yet on the download page we still only advise Bower. We should add a section about using `npm` to get jQuery.

**Comment by dmethvin** [comment]
This was fixed by #123 right?

**Comment by mgol** [comment]
@dmethvin Yeah, this issue will auto-close once the `jquery-3` branch is merged to `master`.

**Comment by mgol** [comment]
Look at the open PRs, some of them start with `[Merged]`, same story.
