### ISSUE TITLE
Adding SRI to code samples on jquery.com

### ISSUE THREAD

**Issue by jonathanKingston** [jquery/jquery.com#124]
See conversation here:
https://github.com/jquery/codeorigin.jquery.com/issues/20#event-585653646

Now the work has happened on code.jquery.com can we have all code samples using SRI?

Thank you, for all your hard work!

**Comment by dmethvin** [comment]
For downloads I think this is addressed by c869920, we're just pointing over to the CDN because the interface there is nice. Are there other places on jquery.com we  need to change? Perhaps some on learn.jquery.com I'd think.

**Comment by dmethvin** [comment]
Closing since I think we got this, if there are places on other sites that need fixing open tickets there.
