### ISSUE TITLE
3.0 Upgrade Guide should consistently reference jQuery

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery.com#130]
The 3.0 Upgrade Guide sometimes uses `$` to represent the `jQuery` function. We should be consistent.

**Comment by dmethvin** [comment]
Yeah, true dat. I was using `$` thinking most people use it that way but the error messages have said `jQuery` for ever so I guess we should go that way.

**Comment by dmethvin** [comment]
I changed all the docs references to `jQuery` and left the code snippets and examples as `$` since that's the way you'd typically write them. I hope that will improve the search relevance.
