### ISSUE TITLE
Remove sections for jQuery 1.x/2.x from the download page?

### ISSUE THREAD

**Issue by mgol** [jquery/jquery.com#132]
Do we want to keep references to the jQuery 1.x/2.x links on the download page once we release jQuery 3.0? This is how they look like now:
https://github.com/jquery/jquery.com/blob/00d89bd63b2951adbe557c416b1e8283839ae30b/pages/download.md#jquery-1x

We should also have a text ready for the 3.x section, perhaps mentioning the upgrade guide for 3.0 as the 1.x entry currently does for 1.9.

@jquery/core?

**Comment by timmywil** [comment]
Yup, we'll remove those for 3.0 final. Mentioning the upgrade guide is good idea.

**Comment by mgol** [comment]
This has been done in f092234043eaf25af346dddcd130752698e46e8e.
