### ISSUE TITLE
Obsolete instructions to publish plugins

### ISSUE THREAD

**Issue by teo1978** [jquery/jquery.com#134]
I just wasted my time following these instructions:
https://plugins.jquery.com/docs/publish/
to publish a plugin. Then I went to http://plugins.jquery.com/ and found out that:

> The jQuery Plugin Registry is in read-only mode. New plugin releases will not be processed.
> We recommend moving to npm, using "jquery-plugin" as the keyword in your package.json. The npm blog has instructions for publishing your plugin to npm.

That same message should replace the contents of https://plugins.jquery.com/docs/publish/.

**Comment by dmethvin** [comment]
We have information duplicated across multiple sites, unfortunately, and nobody seems to have found this before. Thanks!
