### ISSUE TITLE
3.1.0 is released, but on the index and download pages 3.0.0 is the latest

### ISSUE THREAD

**Issue by vkeranov** [jquery/jquery.com#142]
We have 3.1.0 released on 7th of july. Still no update on the index page. The same is on download page. The only information about the latest stable release can be found in the blog, or when checking the releases on Github.

**Comment by mgol** [comment]
Thanks for the report, I updated the links.

@timmywil It seems you've missed some of the steps at https://github.com/jquery/jquery/wiki/Release-process

**Comment by mgol** [comment]
> The only information about the latest stable release can be found in the blog, or when checking the releases on Github.

@vkeranov BTW, there is also npm & bower.

**Comment by vkeranov** [comment]
@mgol, you're right. Sorry, I've missed those. And thanks for the quick response.

**Comment by timmywil** [comment]
Woops! I think it was just that one step, though.
