### ISSUE TITLE
live website is not showing jQuery 3.1.0

### ISSUE THREAD

**Issue by andyli** [jquery/jquery.com#143]
The [download page](http://jquery.com/download/) is still showing jQuery 3.0.0 instead of 3.1.0.
Look like there is something wrong in the deployment process?

**Comment by mgol** [comment]
Thanks for the report! It should be fine now.

@dmethvin This was most likely the older `v3.0.5` tag that you pushed, the site updated to its state. I thought the versions are compared and that you can't "downgrade" the site but apparently you can. I pushed a new tag.
