### ISSUE TITLE
unbind accepts several event types

### ISSUE THREAD

**Issue by PhiLhoSoft** [jquery/jquery.com#146]
I read the [`unbind`](http://api.jquery.com/unbind/) documentation. I use `unbind` instead of `off`, because I work on a legacy project.
Anyway, I see the [`bind`](http://api.jquery.com/bind/) doc defines `eventType` as "_A string containing one or more DOM event types_", while `unbind` defines it as "_A string containing a JavaScript event type_".
So it is unclear if we can specify several event types in `unbind`.
I tried the example of the page, adding `mouseenter` to `click`, and it worked.
So I suggest to update the doc to reflect this fact. Or to openly discourage this practice, if it is frowned upon... (but parameterless `unbind` is "worse", so...)

**Comment by mgol** [comment]
Could you open an issue at https://github.com/jquery/api.jquery.com/issues/? This repo is for the bare https://jquery.com only.

**Comment by mgol** [comment]
It seems a lot of people mistakenly report issues here instead of the API repo; I've created an issue to make it clearer to reporters in which cases this repo is not the correct place: #147.
