### ISSUE TITLE
Homepage: Information on footprint could be misleading

### ISSUE THREAD

**Issue by Chealer** [jquery/jquery.com#148]
The homepage contains:
>Lightweight Footprint

>Only 32kB minified and gzipped. Can also be included as an AMD module

I tried to identify why our intranet took over half a second to load, most of which was not from PHP. There are in the end several reasons, but jQuery took more than I thought. It's hard to say precisely, but just evaluating jQuery UI and jQuery 1.10 on a fairly performant PC (2 years old AMD A8-5600K APU) takes over 10 cs.

Now, I acknowledge that jQuery UI is not "jQuery Core". At 46 ms, I would not call jQuery Core 1.10 heavyweight. Furthermore, http://modernweb.com/2014/03/10/is-jquery-too-big-for-mobile/ suggests I would get much better evaluation times (which might reach under 1 cs) with jQuery 2.1.

On the other hand, I did not realize I was adding such a footprint to the intranet when I included jQuery and jQuery UI by default. And I did think about performance. But - and I reckon I might have been ignorant/careless then - I thought the main impact would be the time taken to fetch jQuery (HTTP). And since our server is local, that was a non-issue. I absolutely did not see script evaluation time.

However, looking at the quote above, I can understand why someone would only think about download time. While download time is indeed much more important on first load (although it has been pointed out that using CDN-s, even the first load may not require downloading jQuery), in the end, evaluation is much more important. If we want to quantify footprint by size, we should make the standard or minified size (probably the latter indeed) at least as prominent as the gzipped size. My recommendation would be to replace the gzipped size with the uncompressed minified size.

**Comment by dmethvin** [comment]
> Now, I acknowledge that jQuery UI is not "jQuery Core". 

And also it's not the other code or resources on the page, which can frequently contribute more to initial page load time.

> My recommendation would be to replace the gzipped size with the uncompressed minified size.

You can measure performance by many measures and it's up to you as the creator of the page to measure/mitigate those. We're not going to put a dent in that understanding with a line or two on the home page of the jQuery web site. The exact size of the file is easily available for each version.

**Comment by Chealer** [comment]
dmethvin, why did you close this ticket?

**Comment by Chealer** [comment]
This is now tracked in ticket #149.
