### ISSUE TITLE
ssl certificate issue from certain browsers

### ISSUE THREAD

**Issue by torydouglas** [jquery/jquery.com#150]
Hello, 

Today i starting seeing a certificate issue when trying to download https://code.jquery.com/jquery-1.10.2.min.js    This is throwing an error in certain browsers (IE Edge)   "There's a problem with this website's security certificate."    This is breaking our site in these browsers.   
![error](https://cloud.githubusercontent.com/assets/15892901/19360611/1980f46e-9134-11e6-8835-761b1b32fd3a.png)

**Comment by dmethvin** [comment]
Dup of https://github.com/jquery/jquery/issues/3359
