### ISSUE TITLE
should references to JSHINT be updated in favor ESLINT ?

### ISSUE THREAD

**Issue by michange** [jquery/jquery.com#155]
The former can't be seen on jq core github. I can't see any .jshintrc file in the source.

So i can't grasp the instructions at : 
https://contribute.jquery.org/style-guide/js/#linting

What should I do in order to lint correctly ?

**Comment by mgol** [comment]
jQuery Core & QUnit has switched from JSHint+JSCS to ESLint with the [`jquery` config](https://www.npmjs.com/package/eslint-config-jquery); I don't know what are plans of other projects ([jQuery UI](https://github.com/jquery/jquery-ui), [jQuery Mobile](https://github.com/jquery/jquery-mobile), [PEP](https://github.com/jquery/PEP)).

Perhaps we should mention both then, at least for the time being. @scottgonzalez, @arschmitz, do you plan to switch other projects eventually? If so, maybe it'd be best to emphasize ESLint and only mention that some projects still use JSHint.

**Comment by scottgonzalez** [comment]
We plan on switching jQuery UI to standard.

**Comment by michange** [comment]
Thanks a lot.

I think the ESLint 'jquery' config mentioned by mgol does not check the whole guide, i.e. the multi-line chain of method calls.

Maybe a little cookbook should be provided on that topic?

**Comment by mgol** [comment]
> I think the ESLint 'jquery' config mentioned by mgol does not check the whole guide, i.e. the multi-line chain of method calls.
> 
> Maybe a little cookbook should be provided on that topic?

This is already mentioned at https://contribute.jquery.org/style-guide/js/#chained-method-calls. It's true we don't validate everything but it's often a side-effect of our tools not being able to do it all for us.

That said, considering @scottgonzalez's reply, various jQuery projects will use incompatible code styles so we should perhaps just remove the whole JSHint description in favor of a short info that each project uses their own linter and that running `npm test` should, among other things, fire up the linter.

**Comment by dmethvin** [comment]
Moved to https://github.com/jquery/contribute.jquery.org/issues/141
