### ISSUE TITLE
Current Version Number Inconsistency

### ISSUE THREAD

**Issue by SteveTheTechie** [jquery/jquery.com#160]
The current version number on jquery.com page and on the downloads page still shows as 3.2.0 ... The only place I am seeing a link to get 3.2.1 is on the blog page.   Since my impression is that 3.2.0 had some regressions in it (per the blog page), I would not think you would want people to continue to download that version.

I thought I must be seeing things... I tried three different browsers (cleared my cache)--no difference.  I also looked at the content in this repo... it looks fine.   Maybe there was a build hiccup somewhere?

**Comment by mgol** [comment]
Thanks for the report! We did update the correct pages but you're right something must have happened with the build process. I triggered a new build and those two pages look fine now.

**Comment by timmywil** [comment]
Thanks! @dmethvin @scottgonzalez Is there an existing email list somewhere that gets notifications of build failures for jquery.com? I'd like to be added to that list if so.
