### ISSUE TITLE
Are jQuery 1.x and 2.x officially end of life?

### ISSUE THREAD

**Issue by willc** [jquery/jquery.com#162]
I ask, because I can't find any official statement about ongoing patches or maintenance of the 1.x and 2.x series, except for this thread, where it seems to be declared:

https://github.com/jquery/jquery/issues/2432#issuecomment-290983196

If I interpret that correctly, the identified vulnerability will not get fixed in the 1.x or 2.x series of jQuery, and the official stance is to upgrade to 3.x. Is that correct?

**Comment by mgol** [comment]
Yes, they're EOL. The issue template that appears when you open a new issue at https://github.com/jquery/jquery/issues contains the following text:

> Note that we only can fix bugs in the latest version of jQuery.

I assume you'd like to see something on the site as well. Do you have a suggestion where you'd want this info and how it should sound?

> If I interpret that correctly, the identified vulnerability will not get fixed in the 1.x or 2.x series of jQuery

We don't give any guarantees for jQuery 1.x/2.x - they're officially unsupported - but if a serious vulnerability was detected (& sent to security@jquery.com) we might reconsider a patch.

**Comment by willc** [comment]
Thanks for the info.

> I assume you'd like to see something on the site as well. Do you have a suggestion where you'd want this info and how it should sound?

A blog post or official announcement of some sort would be helpful.

**Comment by mgol** [comment]
cc @timmywil

**Comment by timmywil** [comment]
We're going to add a note on the homepage that 1.x and 2.x no longer receive patches.

**Comment by willc** [comment]
Thanks...looking forward to it.

**Comment by willc** [comment]
Just curious for when we can expect this announcement to be made on the homepage.

**Comment by mgol** [comment]
A PR is available to review at #163.

**Comment by dmethvin** [comment]
Fixed by #163
