### ISSUE TITLE
3.0 upgrade guide doesn't mention breaking change to TABLE/TBODY under manipulation

### ISSUE THREAD

**Issue by rmacfadyen** [jquery/jquery.com#171]
per: JQuery 3.1.1 vs 2.2.4 change in behavior appending rows to a table https://github.com/jquery/jquery/issues/3976

The following code:

$('&lt;TABLE />').append('&lt;TR>&lt;TD>1&lt;/TD>&lt;/TR>').appendTo('BODY');
results in slightly different DOM structures.

Under 2.2.4 you get &lt;TABLE>&lt;TBODY>&lt;TR>...

Under 3.1.1 you get &lt;TABLE>&lt;TR>...

(one has a TBODY and one does not)

This causes problems if you later have selectors like #id TBODY TR (to get all the body rows, and no header rows).

Apparently the fix for https://github.com/jquery/jquery/issues/1835 in 3.0.0 is why.

Not sure what the upgrade guide should say though (I really don't understand the scope or the reason why #1835 resulted in this change). It did affect my upgrade of some code (unexpectedly)... and I had reviewed the upgrade guide specifically looking for breaking changes before upgrading.

Maybe something like "document fragment of a single TABLE element will no longer have a TBODY created automatically"?

**Comment by noxo** [comment]
dupe to #232

**Comment by mgol** [comment]
Closing as a duplicate
