### ISSUE TITLE
SSL issue on code.jquery.com

### ISSUE THREAD

**Issue by JasonGoemaat** [jquery/jquery.com#172]
Some websites were breaking for me and I tracked it down to this.  The SSL cert is coming back ssl.hwcdn.net so my browsers won't load jquery from the site:

[https://www.ssllabs.com/ssltest/analyze.html?d=code.jquery.com](https://www.ssllabs.com/ssltest/analyze.html?d=code.jquery.com)

**Comment by dmethvin** [comment]
Duplicate of https://github.com/jquery/codeorigin.jquery.com/issues/34
