### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by PanderMusubi** [jquery/jquery.com#174]
Please, fix broken links on the website found by W3C's link checker:

https://validator.w3.org/checklink?uri=http%3A%2F%2Fjquery.com&hide_type=all&recursive=on&depth=&check=Check

**Comment by Krinkle** [comment]
Seems to look fine now. There are a few harmless warnings about redirects and hash fragments (both of which work fine), but no 404 errors or unreachable domains that I can see.
