### ISSUE TITLE
Remove link to Try jQuery from homepage resources

### ISSUE THREAD

**Issue by jonfriskics** [jquery/jquery.com#176]
On June 1, 2018, Code School will be shutting down and the existing Try jQuery course is not being migrated to Pluralsight. I'm on the Code School/Pluralsight team.

You'll also want to remove whatever DNS setting is pointing to the course from `http://try.jquery.com/`

**Comment by mgol** [comment]
We'll handle the DNS change separately. Thanks for the report!
