### ISSUE TITLE
code.jquery.com lacks IPv6 support

### ISSUE THREAD

**Issue by tambry** [jquery/jquery.com#178]
The jQuery CDN `code.jquery.com` lacks IPv6 addresses and thus resources from it can't be received using IPv6.

The CDN seems to be served by StackPath (previously Highwinds), which has recently gotten IPv6 support, so this should be fixable. For reference, [BootstrapCDN](https://www.bootstrapcdn.com) also uses StackPath, and they recently enabled IPv6 for their CDN endpoint (`stackpath.bootstrapcdn.com`).

PS  
Apologies if this is the wrong place to report this, but there doesn't seem to be any place to report issues related to `code.jquery.com`.

**Comment by mgol** [comment]
Hi. `code.jquery.com` is handled via https://github.com/jquery/codeorigin.jquery.com so its issues are best reported there. I know it's not the most intuitive as the name doesn't fully match.

I migrated this issue there: https://github.com/jquery/codeorigin.jquery.com/issues/51

**Comment by tambry** [comment]
Thanks for moving this to the right place!
