### ISSUE TITLE
deferred.then() documentation is not updated

### ISSUE THREAD

**Issue by maria-dimitrova** [jquery/jquery.com#182]
The example 'Filter reject value:' in [jquery.com](https://api.jquery.com/deferred.then/) is not updated to the last jQuery version and it is not correct. It will be good example to show several chained 'then' methods.

When the first 'then' is rejected, it should return new rejected promise to execute the second failCallback of the 'then'.

**Comment by mgol** [comment]
Thanks for the report. However, this repo contains only https://jquery.com code, https://api.jquery.com is located at https://github.com/jquery/api.jquery.com. Can you re-submit the issue there?
