### ISSUE TITLE
.closest not working as expected anymore in v3.3.1

### ISSUE THREAD

**Issue by BananaAcid** [jquery/jquery.com#185]
I used to do something like this, prior to v3.3.1 :
```js
//HTML:   main > ul > li > a

$parent = $('main > ul');

$('li > a').on('click', function() {
  $(this).closest('> li', $parent).css('color', 'red');
});
```
does not work anymore - i have to use `.closest( $('> *', $parent) )`

**Comment by mgol** [comment]
This is a repo for the jquery.com page. jQuery issues should be reported at https://github.com/jquery/jquery. Please remember to create a test case on jsbin.com. Thanks!
