### ISSUE TITLE
jQuery Forums

### ISSUE THREAD

**Issue by MichaelWehar** [jquery/jquery.com#188]
This might not be super relevant, but I wasn't sure where else to post this.

I tried to register for the jQuery Forum.  I think it allowed me to register with Google Sign-in, but then all of the sudden pages started to say: "You are Blocked!" & "404 Sorry!!!".

I found it strange because I had literally just registered 10 minutes earlier.

I tried to re-register without Google Sign-in, but it then took me to a Zoho support page.

Has anyone heard of this before or know what might have caused this?

**Comment by MichaelWehar** [comment]
@JakeCigar Hi Jake!  I thought you might know the answer to this.  Thank you.  :)

**Comment by JakeCigar** [comment]
The forum is not a place to advertise services or to lease software.

**Comment by MichaelWehar** [comment]
@JakeCigar Thank you so much for the reply!  I really appreciate it.

So my account was blocked because I posted something that broke the rules?  Is that what happened?

I'm sorry, I thought I was allowed to share a widget that I made, but I guess that's not what the forum is for.  Rather, that's sort of what the plugin registry is for?

Or, maybe because my widget integrates with a service, that makes it a problem?

Thank you again for your time!

**Comment by MichaelWehar** [comment]
Also, this was a bit confusing because Zoho tries to do a redirect that gets blocked by chrome resulting in the login frame displaying oddly.

**Comment by JakeCigar** [comment]
There are lots of problems with Zoho.  We have no control over their site.

You were blocked for making an off-topic comment to a year old post on 21-Jun-2019.

You’re still blocked.

**Comment by MichaelWehar** [comment]
@JakeCigar Now, I know that I was blocked and your reasoning for blocking.

I won't cause you anymore trouble.
