### ISSUE TITLE
Hitareas on "Other jQuery Foundation Projects" are too small

### ISSUE THREAD

**Issue by jzaefferer** [jquery/jquery.com#19]
Should cover the entire colored area for each link, not just the logo itself.

**Comment by ashg1910** [comment]
in index.html-
<section class="project-tiles row">
    <a href="//jqueryui.com" class="project-tile six columns color secondary-orange">
        <div class="jqueryui small logo"></div>
    </a>
    <a href="//jquerymobile.com" class="project-tile six columns color secondary-green">
        <div class="jquery-mobile small logo"></div>
    </a>
</section>
*******************************
and making adequate changes in the css of the div to display it in the center will do.

Is this a good idea?

**Comment by ashg1910** [comment]
For index.html-
https://gist.github.com/ashg1910/c3da6bea8414a7fe9e87
and making adequate changes in the div to display it in the centre will do.
Is this a good idea?

**Comment by mgol** [comment]
Closed by https://github.com/jquery/jquery-wp-content/pull/413 & https://github.com/jquery/jquery.com/pull/177
