### ISSUE TITLE
Documentation regarding scoped queries: find / add / not / ... in change statements

### ISSUE THREAD

**Issue by cskwg** [jquery/jquery.com#190]
When writing method chaining statements, like
`var table = $( '#first' );
var cells = table.find( 'td' ).add( 'th' );`
the documentation should make clear, that the subsequent method calls loose the scoping.
In the example shown, the first call will scope to the elements of 'table',
but the subsequent 'add' will not. 
So, if there is more than one table on the page, the shown statement will
select the 'td's from the  '#first' table, while the 'add' will all 'th', from the complete page.

**Comment by timmywil** [comment]
Thanks for opening an issue. I think this is already clear in the documentation for the [.add](https://api.jquery.com/add/) method.

> The argument to .add() can be pretty much anything that $() accepts, including a jQuery selector expression, references to DOM elements, or an HTML snippet.

Examples demonstrating how `.add` selects from the document level just like `$()` are included below that.

Finally, issues for documentation should go [here](https://github.com/jquery/api.jquery.com).
