### ISSUE TITLE
Forum broken: can't sign up

### ISSUE THREAD

**Issue by teo1978** [jquery/jquery.com#192]
Go to:
https://forum.jquery.com/jquery-mobile/

Click on the **_"Sign Up"_** button (note the pathetically broken layout btw)

![image](https://user-images.githubusercontent.com/542107/66661075-ab75ca00-ec46-11e9-8c86-02c09499d901.png)

Expected: a sign-up form where I can sign up

Observed: this:

![image](https://user-images.githubusercontent.com/542107/66661128-c47e7b00-ec46-11e9-84df-d3faed8eaae4.png)

(By the way: _"Don't worry though, we will help get you to the right place."_, what the f*** is that supposed to mean?)

**Comment by mgol** [comment]
Going to https://forum.jquery.com/jquery-mobile/ redirects me instantly to https://accounts.zoho.com/signin?servicename=ZohoDiscussions&serviceurl=https%3A%2F%2Fforum.jquery.com. Do you not observe such behavior? Can you try incognito mode?

I'd like to ask you to watch your language. Expressions like "what the f*** is that supposed to mean?" or "pathetically broken layout" are not welcome here. This is not the first time, in various issues you reported in the jQuery repository you used the same derogatory language (e.g. https://github.com/jquery/jquery/issues/3163). You need to stop doing that or we'll have to ask you to stop interacting with us in the jQuery organization on GitHub.

**Comment by teo1978** [comment]
> Going to https://forum.jquery.com/jquery-mobile/ redirects me instantly to https://accounts.zoho.com/signin?servicename=ZohoDiscussions&serviceurl=https%3A%2F%2Fforum.jquery.com. Do you not observe such behavior?

No, but now (in incognito or after logging out) I notice this:

![image](https://user-images.githubusercontent.com/542107/66701364-ed147c80-ecfb-11e9-9cd1-b942903745ab.png)

and after allowing redirects, yes it does, unless I'm already logged in.

A couple of notes:

1. Are you using javascript redirects? Don't do that, use a 302 response.
2. Why redirect in the first place? Users should be able to browse the forum without being logged in, and then log in or sign up if they decide so. By the way, if you have really good reasons (that I can't imagine) for keeping the whole forum only visible to registered users, then again see point 1 and the screenshot above.

**Comment by mgol** [comment]
jQuery Forums are read-only now.
