### ISSUE TITLE
Verify domain on GitHub

### ISSUE THREAD

**Issue by vanillajonathan** [jquery/jquery.com#193]
Change the URL displayed on https://github.com/jquery to use HTTPS.
Set it up as a verified domain.

https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/verifying-your-organizations-domain

**Comment by mgol** [comment]
@dmethvin Could you update the URL?

**Comment by dmethvin** [comment]
Done, thanks!

**Comment by vanillajonathan** [comment]
@dmethvin Can you go through the domain verification process to make it appear as a verified domain on GitHub?

See: https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/verifying-your-organizations-domain

**Comment by dmethvin** [comment]
I don't have access to DNS for the jquery domains. We'll need to go through Linux Foundation for that. @jorydotcom do you know who our contact is there? I may need to coordinate with them if they don't have admin on Github.

**Comment by vanillajonathan** [comment]
@dmethvin, @jorydotcom, any progress?

**Comment by jorydotcom** [comment]
Sorry guys, I missed this notification! We're all set @vanillajonathan @dmethvin
