### ISSUE TITLE
Download link at https://jquery.com/download/

### ISSUE THREAD

**Issue by cakaragiannis** [jquery/jquery.com#197]
Briefly describe the issue you've encountered

An issue with the production download link on the website. Sorry but couldn't see another place to report it.

  *  What do you expect to happen?

Download jquery.

  *  What actually happens?

See attached snippet.

  *  Which browsers are affected?

I tested Firefox Developer edition and Edge Chromium

  Provide a *minimal* test case, see https://webkit.org/test-case-reduction/
  Use the latest shipping version of jQuery in your test case!

No can do for reasons above. Will get from GitHub later.

**Comment by cakaragiannis** [comment]
Oh, really? Sorry about that. See attached.

Thanks. :)

**Comment by mgol** [comment]
Still nothing. I see you reply by email, attaching something there won't work. You need to add it via the GitHub UI.

**Comment by cakaragiannis** [comment]
Okie dokie. Basically, clocking the link to install the latest production
release filled Firefox window with gibberish from top to bottom. Then I
tried in Edge Chromium because sometimes my aggressive security settings
and VPN get in my way. Same result there, too.

Thanks

**Comment by mgol** [comment]
That's just the minified version of jQuery, you need to save it on the disk. You can also right-click on the link and choose "Save Link As...".

I've noticed we use the `download` attribute there but it doesn't work cross-origin which is probably which it's getting skipped here. I'm not sure if we can do anything else here.
