### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by resynth1943** [jquery/jquery.com#208]
## Remove Google Analytics

If you must have an analytics system, might I suggest either:
- Plausible: https://plausible.io (offers a 50% discount for FOSS projects)
- Goatcounter: https://goatcounter.com
- Matomo: https://matomo.org
- Fathom: https://usefathom.org

These solutions are all well-tested and open-source. This, of course, means they
can be independently audited for privacy and security. Instead of using a proprietary
nonfree system such as Google Analytics, perhaps we could work together to replace
it with something slightly more ethical?

Furthermore, the majority of privacy features in evergreen browsers *block* Google
Analytics from being run. I can not say the same for solutions such as Plausible,
which suggests they are trusted for their privacy by independent persons.

If you need any more information, please contact me!

**Comment by mgol** [comment]
Thanks for the report. I'm not sure if we need any analytics solution at all, I haven't seen the collected data so most likely no one is looking at it. I submitted https://github.com/jquery/jquery-wp-content/pull/425 to remove it from content sites.

**Comment by resynth1943** [comment]
Thanks a bunch, @mgol! <3
