### ISSUE TITLE
Cannot login to jQuery forum

### ISSUE THREAD

**Issue by pstein** [jquery/jquery.com#210]
A long time I used the jQuery forum at

https://forum.jquery.com/allforums

When I click now (in newest Firefox) on the "Log in" link I am getting an error from intermediate "Zoho"???

Firefox Can’t Open This Page
To protect your security, accounts.zoho.com will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.

Chrome yields a similar error

Hmm, whats wrong?

How can I successful otherwise?

Peter

**Comment by mgol** [comment]
Thanks for the report. As a workaround, please load the following URL directly:
https://accounts.zoho.com/login?service_language=en&hide_signup=true&servicename=ZohoDiscussions&serviceurl=https://forum.jquery.com&stop_mredirect=true
after you log in, hopefully the forum will work for you.

**Comment by mgol** [comment]
jQuery Forum is read-only now so not being able to log in is expected.
