### ISSUE TITLE
Website Link Broken on About Browser Support

### ISSUE THREAD

**Issue by tobiastromm** [jquery/jquery.com#212]
Hi

I just wanna say that the link on this page https://jquery.com/browser-support/, section "About Browser Support" is pointing to oldversion.com instead of http://www.oldversion.com/.

This is oppening an incorrect website.

Maybe someone can fix the link.

Thanks.

**Comment by mgol** [comment]
The link works fine for me. That said, I think we should remove it. Nowadays the need to have access to older browsers is not that big and a website providing executables via insecure HTTP is something we shouldn't encourage.

**Comment by mgol** [comment]
PR: #230

**Comment by mgol** [comment]
The site is no longer mentioned so I'm closing this issue.
