### ISSUE TITLE
code.jquery.com broken

### ISSUE THREAD

**Issue by muylomas** [jquery/jquery.com#213]
The url https://code.jquery.com/jquery-latest.min.js I use to get the latest jquery script is broken, producing to many redirects when called.

After inspecting a little y found that https://code.jquery.com  has the same issue.

**Comment by mgol** [comment]
Could you provide more details? What's your location? What OS? If Linux or MacOS, can you post what `traceroute code.jquery.com` prints for you?

**Comment by mgol** [comment]
P.S. The script you linked to is **not** the latest jQuery version; it's frozen at 1.11.1, just with worse cache headers. If you really want jQuery 1.11.1, use https://code.jquery.com/jquery-1.11.1.min.js. If you want the latest version, you'll need to update consciously, the current latest is 3.5.1, available at https://code.jquery.com/jquery-3.5.1.min.js.

**Comment by muylomas** [comment]
Thanks mgol for your reply!

I'm trying to reach the url from Uruguay, South America.  Any browser is giving the next problem:
This page isn’t working 
code.jquery.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

I removed all cookies and tried in an incognito window also, but having the same problem.

I'd be interested in being able to access the url as I have some systems where jquery is taken from that url, which takes me a while to redistribute them again.

**Comment by muylomas** [comment]
@mgol could you get in touch with someone who connects that link with a jquery file, so it doesn't get broken?

**Comment by mgol** [comment]
Thanks for your updates. I let relevant people know about this issue, we're trying to find a root cause & fix it.

**Comment by muylomas** [comment]
Great mgol! I resolved the issue for the web site and the Android app, but the broken url originates a bug in my iOS app. It would be great to have the issue solved

**Comment by mgol** [comment]
@muylomas Can you check if it works for you now?

**Comment by muylomas** [comment]
@mgol right now is not working, the same issue is happening. Maybe the changes are still propagating through DNS network.

**Comment by muylomas** [comment]
Hi @mgol, the problem from my location is still happening. I tested the https://code.jquery.com/jquery-latest.min.js from a US proxy (https://www.proxysite.com/) and is working. It is something with the location. My location si:

IP Location: Paso de Carrasco, Canelones (UY) 
Latitude: -34.8603 
Longitud: -56.0522
Host Name: r167-57-181-96.dialup.adsl.anteldata.net.uy
ISP: Administracion Nacional de Telecomunicaciones
Proxy: 167.57.181.96, 198.143.41.25

**Comment by muylomas** [comment]
@mgol, sorry for being so insistent, but could you enable the access of the area where I am to the url https://code.jquery.com/jquery-latest.min.js ?

**Comment by mgol** [comment]
@muylomas We're trying to provide a workaround at the moment (the first version didn't include all locations, it seems). We're also working on a long term solution that will make these issues not happen again.

**Comment by muylomas** [comment]
Hope it gets fixed soon, I'm crossing my fingers 🤞🤞

**Comment by mgol** [comment]
@muylomas Can you check now? If it still fails, can you check on a different browser and after clearing browser cache? This is just so that if it fails, we know whether the fix worked at all and we just need to handle caches now or if it's still broken as it was.

**Comment by muylomas** [comment]
@mgol it's still broken as it was. I check the link in Chrome, Firefox and Safari. I also cleared all site data, having the same result. I used desktop and mobile devices, having the same results.

**Comment by mgol** [comment]
Thanks for the update. We'll investigate further.

**Comment by muylomas** [comment]
@mgol thanks to you and always available for whatever you need.

**Comment by mgol** [comment]
@muylomas https://github.com/jquery/codeorigin.jquery.com/issues/67 covers this issue and has more people involved so let's move the discussion there.

**Comment by muylomas** [comment]
Thanks @mgol, hopes it get fixed!! Thanks for tacking care of the issue
