### ISSUE TITLE
[Critical] Not able to download the https://code.jquery.com/jquery-3.4.1.min.js due to certificate issue

### ISSUE THREAD

**Issue by vkb1** [jquery/jquery.com#220]
Since yesterday, the wget command that fetches the jquery library is failing with below issue:
```sh
$ wget https://code.jquery.com/jquery-3.4.1.min.js
--2021-07-29 16:51:26--  https://code.jquery.com/jquery-3.4.1.min.js
ERROR: cannot verify code.jquery.com's certificate, issued by ‘emailAddress=proxy.engineering@intel.com,CN=NSE sha2,OU=Network Services Engineering,O=Proxy Engineering,ST=Oregon,C=US’:
  Self-signed certificate encountered.
To connect to code.jquery.com insecurely, use `--no-check-certificate'.
```
Looks like the site certificate needs to be updated. Can this be addressed at the earliest?

**Comment by mgol** [comment]
We're not using a certificate like that; looks like a MITM done by your own employer, please raise it internally at Intel.

**Comment by mgol** [comment]
(hint: `emailAddress=proxy.engineering@intel.com`)

**Comment by vkb1** [comment]
Thanks @mgol , let me get this resolved internally...
