### ISSUE TITLE
"Quick Access" Download is Outdated

### ISSUE THREAD

**Issue by dcherman** [jquery/jquery.com#54]
The "Quick Access" link to download jQuery at the bottom of each page looks to be outdated by a version.  Should this be kept up to date with each final release?

![image](https://f.cloud.github.com/assets/976608/2012425/61c366fc-8788-11e3-9049-5d47430f83ec.png)

**Comment by phpPluginMaster** [comment]
Where did the link go, it's not on the website for some reason.
