### ISSUE TITLE
Corporate Logos styling fix

### ISSUE THREAD

**Issue by jenstrickland** [jquery/jquery.com#70]
Related to issue, https://github.com/jquery/jquery.com/issues/53#event-120707262. At smaller viewport sizes the logos get smaller, sometimes too small and look bad, and then at phone size, the logos align to the left. It would be better if the logos don't get smaller than a reasonable size, and that the logos center align.
Phone:
![screen shot 2014-05-13 at 3 52 08 pm](https://cloud.githubusercontent.com/assets/57469/2963178/215da37c-dad8-11e3-8617-f430cdcd2d32.png)
Full Width:
![screen shot 2014-05-13 at 3 51 47 pm](https://cloud.githubusercontent.com/assets/57469/2963179/21625b1a-dad8-11e3-8cbd-01d0fa7f4123.png)
Medium Width:
![screen shot 2014-05-13 at 3 51 57 pm](https://cloud.githubusercontent.com/assets/57469/2963177/215cf3be-dad8-11e3-93d0-b412ca572d9e.png)

**Comment by phiju123** [comment]
Use of max-width & min-height can help.
