### ISSUE TITLE
Use https for download links

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery.com#86]
Right now we use http for downloading even if the user came in via https. Now that the CDN supports https we should use it, at the very least when the user comes in via a secure connection, by removing the protocol from all the downloady links.

**Comment by fabiosantoscode** [comment]
Protocol relative links don't work so well under file:// ...

**Comment by mzgol** [comment]
What's the use-case of relative protocol urls at this date, by the way?
What's the drawback of just using https everywhere?

-- 
Michał Gołębiowski

**Comment by dmethvin** [comment]
I don't think `file://` would be a problem for this case. I'm fine with relative links, or https.

**Comment by arthurvr** [comment]
These days protocol-relative URLs is totally anti-pattern indeed. We recently switched everything over in HTML5 boilerplate as well. I'm :+1: for https always.

**Comment by mgol** [comment]
It seems everyone is in favor. We even have a PR: #116. Can we rebase & land it?

**Comment by AurelioDeRosa** [comment]
@mgol If you want I can take of the PR. Let me know.

**Comment by mgol** [comment]
Sure, I'll handle it.

**Comment by AurelioDeRosa** [comment]
@mgol I've just realized that probably there is nothing I should do other than asking the user to rebase. If the user won't do it, then I can take an action. Do you agree?

**Comment by mgol** [comment]
Sure.
