### ISSUE TITLE
incorrect, conflicting documentation

### ISSUE THREAD

**Issue by jkieley** [jquery/jquery.com#89]
on http://api.jquery.com/jquery.contains/

The api doc at the top says: "jQuery.contains( container, contained )"
but in the example (and working code) it shows:
$.contains( document.documentElement, document.body ); // true
$.contains( document.body, document.documentElement ); // false

demonstrating that in fact the **second argument** is the **container**

**Comment by arschmitz** [comment]
@jkieley quite the opposite `document.documentElement` is the `html` element which contains the `body` hence the first element is the container.
