### ISSUE TITLE
JQUERY CDN DOWN

### ISSUE THREAD

**Issue by flapflapflap** [jquery/jquery.com#90]
Is the code.jquery.com down or broken or so? :-1: 

Giving me an infinite loop in the console.

**Comment by gnarf** [comment]
I'm having no trouble, where are you trying to reach it from?

**Comment by arthurvr** [comment]
@gnarf There are actually more people having trouble. Many people are complaining in #jquery [and on twitter](https://twitter.com/search?q=code.jquery.com&src=typd). Also https://github.com/jquery/jquery/issues/2156.

**Comment by kborchers** [comment]
I think it may be fixed. Haven't seen a complaint for about an hour and http://status.maxcdn.com says all is ok though they were investigating a routing issue which was the likely culprit but haven't updated for about an hour
