### ISSUE TITLE
jqHXR cant abort XMLHTTPRequest

### ISSUE THREAD

**Issue by workhours** [jquery/jquery.com#99]
var request=$.ajax({..., dataType:"script"});
request.abort(); //this line can't function correctly. If we trace into this function, we see abort() inside of jQuery.ajaxTransport( "script",function(s){...}) is called, but real xhr.abort() is defined in jQuery.ajaxTransport.(function(options){...})

**Comment by dmethvin** [comment]
The "..." part is pretty important to a repro case. Can you post a complete example on jsbin.com?

**Comment by dmethvin** [comment]
Oh, you're at the wrong repo anyway. You want jquery/jquery, but again don't open an issue without a test case. Thanks.

**Comment by workhours** [comment]
http://jsbin.com/mulicolowe/edit?html,js,output
